### ISSUE TITLE
Email?

### ISSUE THREAD

**Issue by RealRainbowDoge** [Backdoorek/Librus-Tricks#1]
Jak mam się zalogować do synergii za pomocą emaila? Na oficjalnej stronie pytają o login, a email powiązany z kontem nie działa.

**Comment by Backdoorek** [comment]
@RealRainbowDoge na pewno podajesz email do konta na Librus Portal?
U mnie wszytko działa
![image](https://user-images.githubusercontent.com/30326322/58498951-63ff0d80-817f-11e9-87d2-425cd1e5cc6e.png)

**Comment by RealRainbowDoge** [comment]
Ano właśnie, chodzi o email do konta Librus, czy do konta Synergia? Bo to dość ważna różnica

**Comment by RealRainbowDoge** [comment]
Podejrzewam, że chodzi o Librus, ale zaznacz to w takim razie w docsach, bo przez dłuższą chwilę zastanawiałem się o co chodzi ;)

**Comment by Backdoorek** [comment]
Chodzi o email i hasło do Portal Librus. Te same dane co podajesz w aplikacji mobilnej. Jeszcze nie zacząłem prac nad logowaniem tylko przy użyciu danych do Synergii.
