### ISSUE TITLE
Logowanie do Synergii

### ISSUE THREAD

**Issue by michalelektryk** [Backdoorek/Librus-Tricks#12]
Dokumentacja jest trochę szczątkowa, więc nie do końca ogarniam jak zautoryzować się do Synergii. Za każdym razem dostaję bład, że to jest haśło do Synergii, a nie do librusa

**Comment by Backdoorek** [comment]
Opisałem to w #1 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
