### ISSUE TITLE
[HELP] Brak możliwości zalogowania kontem rodzica

### ISSUE THREAD

**Issue by chomar83** [Backdoorek/Librus-Tricks#17]
## Problem
Nie mogę się zalogować loginem i hasłem rodzica do synergii.
Czy biblioteka obsługuje też konta rodzica?

## Jak odtworzyć błąd
from librus_tricks import create_session
session = create_session('login_rodzica','haslo_rodzica')

## Stacktrace
```
session = create_session('login_rodzica', 'haslo_rodzica')
  File "C:\Users\Marcin\.conda\envs\privdev\lib\site-packages\librus_tricks-0.7.6-py3.7.egg\librus_tricks\__init__.py", line 24, in create_session
  File "C:\Users\Marcin\.conda\envs\privdev\lib\site-packages\librus_tricks-0.7.6-py3.7.egg\librus_tricks\auth.py", line 178, in authorizer
librus_tricks.exceptions.LibrusPortalInvalidPasswordError: {'errors': ['Upewnij się, że nie wpisujesz tutaj loginu i hasła otrzymanych ze szkoły! Są to dane do systemu SYNERGIA, nie do Konta LIBRUS!'], 'captchaRequired': False}
```

## Środowisko
  Windows 10

**Comment by Backdoorek** [comment]
Dopóki nie powiążesz konta Synergia z kontem Librus Portal. Biblioteka nie wspiera logowania poprzez dane z Synergii. Z tego co mi wiadomo, to konta rodziców z Librus Portal działają bez zarzutów. Jeśli wiesz jak uzyskać token do API nie używając Librus Portal to by było miło jakbyś powiedział jak to zrobić.
