### ISSUE TITLE
[BUG] Problem z rewalidacją

### ISSUE THREAD

**Issue by kapi2289** [Backdoorek/Librus-Tricks#6]
## Problem
System rewalidacji nie działa

## Stacktrace
```
File ".../librus_tricks/core.py", line 70, in get
  }[response.status_code]
librus_tricks.exceptions.SynergiaAccessDenied: {'Status': 'Error', 'Message': 'Request is denied', 'Code': 'TokenIsExpired'}
```

## Środowisko
 - OS: Ubuntu 18.04
 - Wersja pythona: 3.6.8

**Comment by barpec12** [comment]
U mnie ten sam problem, Debian 9 i Python 3.7.4.

**Comment by Backdoorek** [comment]
@barpec12 dzięki za zgłoszenie issue, prawdopodobnie rozwiąże go w najbliższy weekend. Jeśli byś miał jakieś pytanka lub chciał pomóc to zapraszam na [discorda](https://discord.gg/WHY87GR)

**Comment by Backdoorek** [comment]
![image](https://user-images.githubusercontent.com/30326322/65068632-469dbb80-d989-11e9-9f94-bddb22c95a0a.png)
